name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: KimemiaT/vuepress-deploy@master
      env:
        ACCESS_TOKEN:{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}
        TARGET_REPO: KimemiaT/KimemiaT.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/src/.vuepress/index.md
